trixie change, first attempt

diff --git a/imager.sh.tmpl b/imager.sh.tmpl
--- a/imager.sh.tmpl
+++ b/imager.sh.tmpl
@@ -3,6 +3,10 @@
 
 #/# Usage: imager.sh <command> <options>
 #/#
+#/# Options:
+#/#     -n, --dry-run
+#/#         Skip actual work in the image command.
+#/#
 #/# Commands:
 #/#     list-disks [--all]
 #/#         List available disks for imaging. Defaults to physical,
@@ -25,6 +29,7 @@ set -o pipefail
 #{{include fs.sh}}#
 #{{include io.sh}}#
 #{{include setup_config.sh}}#
+#{{include boot_config.sh}}#
 
 ROOT_DIR="$(cd "$(dirname "$0}")" && pwd)"
 
@@ -93,7 +98,7 @@ list_disks() {
                          -extract "AllDisksAndPartitions.${INDEX}.Partitions.0.MountPoint" \
                          raw "${PLIST}" )"
 
-            echo "/dev/${DISK}  ${VOLUME:-?}"
+            echo "/dev/${DISK}: ${VOLUME:-?}"
             TOTAL=$((TOTAL+1))
         done
     fi
@@ -201,11 +206,11 @@ select_image() {
     DEFAULT="$(
         jq -r '.name' "${IMAGELIST}" | \
         nl -s: -w1 | \
-        grep Legacy | grep 64-bit | grep Lite |\
+        grep -v Legacy | grep 64-bit | grep Lite |\
         cut -d: -f1)"
 
     if [[ -n "${DEFAULT}" ]]; then
-        PICK="$(prompt_default "${DEFAULT}" "Select a base image (probably want Legacy Lite)")"
+        PICK="$(prompt_default "${DEFAULT}" "Select a base image (probably want Lite)")"
     else
         PICK="$(prompt "Select a base image")"
     fi
@@ -369,6 +374,13 @@ set_autolaunch_racecapture() {
     fi
 }
 
+# Provide an implementation so that lib/boot_config.sh
+# can find it, but because we're imaging there's no
+# actual reboot necessary.
+reboot_required() {
+    true
+}
+
 # prepare and write an image to the given $1=disk
 image() {
     local DISK="${1:-}"
@@ -479,6 +491,7 @@ image() {
         # Pretend /tmp is our volume.
         VOLUME="/tmp/example-boot-volume"
         mkdir -p "${VOLUME}" || abort "error creating ${VOLUME} for dry-run"
+        touch "${VOLUME}/config.txt"
     else
         # Figure out the volume name of our disk (which is set by the image), and where it lives
         VOLUME="$(list_disks | grep -F "${DISK}" | awk '{print $2}')"
@@ -500,15 +513,55 @@ image() {
     perror
     set_autolaunch_racecapture
 
+    # generate user-data
+    local PI_HOSTNAME="$(prompt_default bdrpi "Specify a host name")"
+    local FIRST_RUN_USER="$(get_setup_config FIRST_RUN_USER)"
+    local FIRST_RUN_PASS="$(get_setup_config FIRST_RUN_PASS)"
+
+    if ! sed -e "s/{{PI_HOSTNAME}}/${PI_HOSTNAME}/; s/{{FIRST_RUN_USER}}/${FIRST_RUN_USER}/; s/{{FIRST_RUN_PASS}}/${FIRST_RUN_PASS}/" "${ROOT_DIR}/resources/user-data.tmpl" >"${VOLUME}/user-data"; then
+        abort "failed to write user-data to ${VOLUME}/user-data"
+    fi
+
+    # keep the user so we configure auto login
+    clear_setup_config FIRST_RUN_PASS
+
+    # generate_network-config
+    local WIFI_COUNTRY="$(get_setup_config WIFI_COUNTRY)"
+
+    if ! sed -e "s/{{WIFI_COUNTRY}}/${WIFI_COUNTRY}/" "${ROOT_DIR}/resources/network-config.tmpl" >"${VOLUME}/network-config"; then
+        abort "failed to write network-config"
+    fi
+
+    local NUM_CONFIGS="$(get_setup_config_array_size WIFI_SSID)"
+    if [[ -n "${NUM_CONFIGS}" ]] && [[ "${NUM_CONFIGS}" -gt 0 ]]; then
+        local IDX=0
+        while [[ "${IDX}" -lt "${NUM_CONFIGS}" ]]; do
+            local SSID PASS
+            SSID="$(get_setup_config_array WIFI_SSID "${IDX}")"
+            PASS="$(get_setup_config_array WIFI_PASS "${IDX}")"
+
+            if ! sed -e "s/{{SSID}}/${SSID}/; s/{{PASSWORD}}/${PASS}/" "${ROOT_DIR}/resources/network-config-ap.tmpl" >>"${VOLUME}/network-config"; then
+                abort "failed to add wifi network to network-config"
+            fi
+            IDX=$((IDX+1))
+        done
+
+        clear_setup_config_array WIFI_SSID
+        clear_setup_config_array WIFI_PASS
+        clear_setup_config_array WIFI_PRIO
+    fi
+
+    # modify config.txt
+    export BDRPI_BOOT_CONFIG_TXT="${VOLUME}/config.txt"
+
+    boot_config_set "all" "dtparam=i2c_arm" "on"
+    boot_config_set "all" "dtparam=audio" "off"
+    boot_config_set "all" "diable_splash" "1"
+    boot_config_set "all" "diable_touchscreen" "1"
+    boot_config_set "all" "gpu_mem" "${BDRPI_GPU_MEM:-256}"
+
     cp "${ROOT_DIR}/resources/firstrun.sh" "${VOLUME}/bdr-pi-firstrun.sh"
     cp "${ROOT_DIR}/docs/setup.sh" "${VOLUME}/bdr-pi-setup.sh"
-
-    if [[ -f "${VOLUME}/cmdline.txt" ]]; then
-        local CMDLINE
-        CMDLINE="$(cat "${VOLUME}/cmdline.txt")"
-        CMDLINE="${CMDLINE} systemd.run=/boot/bdr-pi-firstrun.sh systemd.run_success_action=reboot systemd.unit=kernel-command-line.target"
-        ${SAFE} echo "${CMDLINE}" >"${VOLUME}/cmdline.txt" || abort "unable to write ${VOLUME}/cmdline.txt"
-    fi
 
     perror
     perror "Ejecting ${DISK}..."
