imager.sh script builds a boot image on a local volume:   At imaging time it queries for various configurable   parameters (user; wifi config; lifepo4wered ups config)   and generates an image with a firstrun script that:   - creates the default user   - configures wifi hardware country   - copies setup script to user's home dir   - configures autologin   - arranges for the setup script to be run
implement tests of most of lib scripts

diff --git a/setup.sh.tmpl b/setup.sh.tmpl
--- a/setup.sh.tmpl
+++ b/setup.sh.tmpl
@@ -6,6 +6,7 @@ set -u
 #{{include fs.sh}}#
 #{{include io.sh}}#
 #{{include network.sh}}#
+#{{include setup_config.sh}}#
 
 # Require bash
 # shellcheck disable=SC2292
@@ -18,44 +19,65 @@ if [[ "$OS" != "Linux" ]]; then
     abort "OS is ${OS} -- this isn't going to work out."
 fi
 
-DISTRIBUTION="$(lsb_release -si)"
-if [[ "$DISTRIBUTION" != "Raspbian" ]]; then
-    echo "Expected a Raspbian distribution, but we'll muddle on..."
-fi
-
 if [[ "$(whoami)" == "root" ]]; then
     abort "run this as a normal user with access to sudo"
 fi
 
-REPO="https://github.com/zuercher/bdr-pi"
 BDR_DIR="${HOME}/.bdr-pi"
+mkdir -p "${BDR_DIR}" || abort "could not create dir: ${BDR_DIR}"
 
-if ! network_can_reach "${REPO}"; then
-    perror "unable to reach ${REPO}, retrying for 30 seconds..."
+REPO="https://github.com/zuercher/bdr-pi"
+BDR_REPO_DIR="${HOME}/.bdr-pi/bdr-pi"
+
+FIRST_BOOT=false
+while [[ -n "${1:-}" ]]; do
+    case "$1" in
+        --first-boot)
+            FIRST_BOOT=true
+            shift
+            ;;
+        *)
+            abort "usage: $0 [--first-boot]"
+    esac
+done
+
+NEWTORK_OK=false
+if ! "${FIRST_BOOT}"; then
     N=0
-    NETWORK_OK=false
-    while [[ "${N}" -lt 30 ]] && ! "${NETWORK_OK}"; do
-        N=$((N + 1))
-        sleep 1
-
+    NUM_ATTEMPTS=30
+    while [[ "${N}" -lt "${NUM_ATTEMPTS}" ]]; do
         if network_can_reach "${REPO}"; then
-            NETWORK_OK="true"
+            NETWORK_OK=true
+            break
         fi
+
+        N=$((N + 1))
+        LEFT=$((NUM_ATTEMPTS - N))
+        perror "unable to reach ${REPO}, will retry ${LEFT} more times..."
+        sleep 1
     done
 
     if ! "${NETWORK_OK}"; then
         perror "failed to reach ${REPO}, starting wifi setup..."
-        wireless_network_setup
+
+        if "${FIRST_BOOT}"; then
+            wireless_network_setup --first-boot
+        else
+            wireless_network_setup
+        fi
 
         report "wireless setup complete; waiting for the internet to become reachable..."
 
         N=0
+        NUM_ATTEMPTS=30
         while ! network_can_reach "${REPO}"; do
             N=$((N + 1))
             if [[ "${N}" -ge 60 ]]; then
                 abort "failed to reach ${REPO} for 60 seconds, something's fucky"
             fi
 
+            LEFT=$((NUM_ATTEMPTS - N))
+            perror "unable to reach ${REPO}, will retry ${LEFT} more times..."
             sleep 1
         done
     fi
@@ -73,29 +95,27 @@ if ! installed git; then
     fi
 fi
 
-REPO="https://github.com/zuercher/bdr-pi"
-BDR_DIR="${HOME}/.bdr-pi"
-if [[ -d "${BDR_DIR}/.git" ]]; then
+if [[ -d "${BDR_REPO_DIR}/.git" ]]; then
     # Git repository is present. Let's update it.
-    push_dir "${BDR_DIR}"
+    push_dir "${BDR_REPO_DIR}"
     echo -n "${REPO} "
     git pull || abort "unable to pull $(git remote get-url origin)"
     pop_dir
 else
     # No git repository. Clone it.
-    git clone "${REPO}" "${BDR_DIR}" || abort "unable to clone ${REPO}"
-    push_dir "${BDR_DIR}"
+    git clone "${REPO}" "${BDR_REPO_DIR}" || abort "unable to clone ${REPO}"
+    push_dir "${BDR_REPO_DIR}"
     # So it doesn't complain every time we pull
     git config pull.ff only
     pop_dir
 fi
 
-mkdir -p "${BDR_DIR}/.state" || abort "could not create state dir"
+mkdir -p "${BDR_DIR}/state" || abort "could not create state dir"
 mkdir -p "${BDR_DIR}/logs" || abort "could not create log dir"
 
 SETUP_LOGFILE="${BDR_DIR}/logs/setup_$(date -u "+%Y%m%d_%H%M%S").log"
 
-# Initial setup is complete, now transfer control to the code in BDR_DIR
+# Initial setup is complete, now transfer control to the code in BDR_REPO_DIR
 # Jump through some hoops to set SETUP_FLUSH_PID with script's PID so we
 # can send SIGUSR1 to it (which will flush logs). We also take care to
 # pass along the original user's name, path and tty.
@@ -106,5 +126,6 @@ script --quiet --flush --log-out "${SETUP_LOGFILE}" \
             SETUP_HOME=\"${HOME}\" \
             SETUP_TTY=\"$(tty)\" \
             SETUP_FLUSH_PID=\"\$PPID\" \
+            BDR_REPO_DIR=\"${BDR_REPO_DIR}\" \
             BDR_DIR=\"${BDR_DIR}\" \
-            \"${BDR_DIR}/update.sh\" $*'"
+            \"${BDR_REPO_DIR}/update.sh\" $*'"
